Address issue #263, joint_trajectory_controller - wraparoundOffset
ros-controls/ros_controllers pull request #276
Opened 2017-05-15 13:27 UTC by graiola

2017-05-15 16:57 UTC, ipa-mdl commented on joint_trajectory_controller/test/joint_trajectory_segment_test.cpp
> +
What about checking `wraparoundJointOffset(-M_PI/2, M_PI, true);` as well?

2017-05-15 17:13 UTC, bponsler commented
Thanks for doing this @graiola! I wasn't going to be able to pull this together until later today.

I tested these changes on indigo and they solve the issue I was seeing before. You can see in the below graph that the desired state (red line) no longer has the upward bump seen in #274.

![screenshot7](https://cloud.githubusercontent.com/assets/1627139/26069647/8cb623da-3956-11e7-881d-631b7bf070b6.png)

2017-05-15 17:20 UTC, graiola commented
@bponsler  no problem! I am happy that it solved the problem ;)

2017-05-15 20:13 UTC, ipa-mdl commented
> @ipa-mdl could you run some tests with your robot/s to validate the fix? Thanks.

@graiola: I am sorry, I cannot test it with hardware. I don't have any right now and we don't use wrap-around configs.

2017-05-29 13:07 UTC, graiola commented
@progtologist could you give it a shot? Thanks.

2017-06-01 09:05 UTC, progtologist commented
@graiola I cannot test it with hardware right now but it runs correctly in simulation so I see no reason why it shouldn't work with hardware as well! Great job!

2017-06-16 10:57 UTC, bmagyar requested changes
Ping

2017-06-16 10:57 UTC, bmagyar commented on joint_trajectory_controller/include/joint_trajectory_controller/joint_trajectory_segment.h
> +   // Return value
There's no reason to change this line

2017-06-16 10:57 UTC, bmagyar commented on joint_trajectory_controller/test/joint_trajectory_segment_test.cpp
> +
There's no reason to change this line

2017-06-16 10:57 UTC, bmagyar commented on joint_trajectory_controller/test/joint_trajectory_segment_test.cpp
> +
There's no reason to change this line

2017-06-17 19:56 UTC, bmagyar approved these changes

2017-06-26 10:00 UTC, bmagyar commented
We are almost there! ;) 

Could you tell me what's the difference between the two "Added tests for issue #275" commits? They look the same to me. 
Could you remove one of them and the "merge branch blabla" commit as well?

2017-06-26 12:09 UTC, graiola commented
I removed the rqt_plot because it was causing problems with travis.

2017-06-27 10:01 UTC, bmagyar commented
Great, thanks!

2017-06-27 10:01 UTC, merged