Fix for issue #275
ros-controls/ros_controllers pull request #277
Opened 2017-05-16 01:42 UTC by bponsler

Fix for issue #275 (State error calculation not accounting for wrapping joint positions).

Created an additional test case to test a robot with wrapping continuous joint angles.

2017-05-16 01:44 UTC, bponsler commented
This is for indigo since I don't have a quick way to compile/test for kinetic.

2017-05-16 06:53 UTC, ipa-mdl commented
I have restarted [one job](https://travis-ci.org/ros-controls/ros_controllers/jobs/232655977) because of an unrelated error:
```
[diff_drive_controller.rosunit-diff_drive_odom_frame_test/testOdomTopic][FAILURE]
/root/catkin_ws/src/ros_controllers/diff_drive_controller/test/diff_drive_odom_frame_test.cpp:73
Value of: "new_odom"
Expected: odom_msg.header.frame_id.c_str()
Which is: ""
```

2017-05-16 11:06 UTC, graiola commented
I try to run the fix on kinetic to see how it behaves.

2017-05-16 12:21 UTC, bmagyar commented
Are you running this on Indigo? Do you have trouble on Indigo because of this? 
I'm a bit reluctant to add new stuff to Indigo that potentially changes behaviour but this can be considered bug fixing.

2017-06-16 12:57 UTC, bmagyar requested changes

2017-06-16 12:57 UTC, bmagyar commented on joint_trajectory_controller/test/joint_trajectory_controller_wrapping_test.cpp
> +// Copyright (C) 2013, PAL Robotics S.L.
You may want to adjust the name here

2017-06-16 16:46 UTC, bponsler commented on joint_trajectory_controller/test/joint_trajectory_controller_wrapping_test.cpp
> +// Copyright (C) 2013, PAL Robotics S.L.
Who do you want this copyright attributed to? I'll also adjust the year to 2017 unless you disagree.

2017-06-19 17:04 UTC, graiola commented
Hi @bponsler thanks for the fix! Could you please split the commit between the fix and the test? In this way we can cherry-pick the test on kinetic too!

2017-06-21 22:02 UTC, bponsler commented
Sure thing. Let me know if you want me to do anything else

2017-06-22 08:27 UTC, graiola commented
Thank you Brett!

2017-06-27 10:03 UTC, bmagyar commented on joint_trajectory_controller/test/joint_trajectory_controller_wrapping_test.cpp
> +// Copyright (C) 2013, PAL Robotics S.L.
Up to you. If it was on your own time, you can leave it like that or if it's within a company you may want to add them there. It's a test, hence it doesn't matter much.

2017-06-27 21:17 UTC, bponsler commented on joint_trajectory_controller/test/joint_trajectory_controller_wrapping_test.cpp
> +// Copyright (C) 2013, PAL Robotics S.L.
I'm fine with it as is, thanks for the suggestion though!

2017-06-28 09:00 UTC, bmagyar approved these changes

2017-06-28 09:21 UTC, merged

2017-06-28 09:22 UTC, bmagyar commented
Thanks Brett!