Remove deprecated warning.
ros-controls/ros_controllers pull request #386
Opened 2018-11-21 18:03 UTC by AndyZe

2018-11-21 18:35 UTC, bmagyar approved these changes
Thanks for this.
Even though I'm approving now the CI may still fail if we have tests directly aimed at this. If any, those will need to be removed.

2018-11-21 18:40 UTC, bmagyar requested changes
This change also removes the parameter we'd like to keep :)

2018-11-22 13:24 UTC, mathias-luedtke commented on joint_trajectory_controller/include/joint_trajectory_controller/joint_trajectory_controller_impl.h
> +  controller_nh_.getParam("stop_trajectory_duration", stop_trajectory_duration_);
For semantic reasons I'd prefer
```
stop_trajectory_duration_ =  controller_nh_.param("stop_trajectory_duration", 0.0);
```

2018-11-22 13:36 UTC, ipa-mdl commented
Tests pass again, `hold_trajectory_duration` is not used elsewhere (in our repos).
`https://github.com/ros-industrial/ur_modern_driver` still has the old parameter name, but commented out.

2018-11-22 15:11 UTC, bmagyar approved these changes
Other than the point @ipa-mdl raised I'm happy with the PR. Please feel free to merge once done

2018-11-24 21:33 UTC, ipa-mdl commented on joint_trajectory_controller/include/joint_trajectory_controller/joint_trajectory_controller_impl.h
> +  controller_nh_.getParam("stop_trajectory_duration", stop_trajectory_duration_);
There is a copy&paste bug in the new commit. I rolled back to the original version again.
In addition the other parameters are retrieved the same way, so let's keep it like this for now.

2018-11-25 01:33 UTC, merged