Print error messages for all exceptions in `joint_trajectory_controller`
ros-controls/ros_controllers pull request #414
Opened 2019-04-02 21:19 UTC by ianjfrosst

When initializing a trajectory, multiple different exceptions can be thrown. Having `catch(std::invalid_argument)` followed by `catch(...)` drops all information about any exceptions that aren't `std::invalid_argument`.

2019-04-03 13:13 UTC, bmagyar requested changes
I like the proposed changes. Could you please submit it against `melodic-devel` first? 
I will cherry-pick it to kinetic from there.

2019-04-03 17:11 UTC, ianjfrosst commented
@bmagyar rebased the branch against `melodic-devel`. If you want me to make a new PR instead, I can do that, too.

2019-04-08 19:52 UTC, mathias-luedtke approved these changes

2019-04-08 20:38 UTC, bmagyar approved these changes

2019-04-08 20:38 UTC, bmagyar commented
Thanks for this, merging!

2019-04-08 20:38 UTC, merged

2019-04-08 20:40 UTC, bmagyar commented
I've also cherry-picked it to kinetic ;)