Compliance Controller Improvements
ros-controls/ros_controllers pull request #434
Opened 2019-10-30 20:10 UTC by AdamPettinger

This is an update to this pull request to kinetic-devel: [(WIP) New type of compliance controller #393](https://github.com/ros-controls/ros_controllers/pull/393).

Updated to Melodic, added singularity checking, and improved directionally constrained compliance.

Tested on UR5 with ATI Gamma Force/Torque sensor. Videos showing improved directional control:

1. [Compliant only in EEF Forward and EEF roll directions](https://drive.google.com/file/d/1i77SVG8YFoIGYAzKRylypvYj8J8b838f/view?usp=sharing)
2. [Grasping a valve with compliance](https://drive.google.com/file/d/1FAsqDhwRbRmkkmAsjUnJbrf_N2DZzJQ1/view?usp=sharing) and no other user input

2019-11-12 22:35 UTC, bmagyar commented
Thanks for this guys. Would it be possible to squash/rebase this PR to reduce the number of commits (and potential conflicts)?

2019-11-12 22:51 UTC, bmagyar requested changes
First of all, thanks for contributing!! 

Please ensure that you only change code in the files you are adding. Specifically changelogs shouldn't be touched. There's a new Git modules file added, please get rid of it. Make sure you are listed as author and maintainer in each package and please add me as maintainer as well.

I haven't finished with the review but wanted to post these comments so you have some feedback.

2019-11-12 22:51 UTC, bmagyar commented on compliance_controller/README.md
> +* Clone NRG's ros_controllers repo (kinetic-compliance branch), https://github.com/UTNuclearRobotics/ros_controllers
Needs an update?

2019-11-12 22:51 UTC, bmagyar commented on compliance_controller/compliance_control_msgs/package.xml
> +  <maintainer email="andyz@utexas.edu">AndyZe</maintainer>
Missing author

2019-11-12 22:51 UTC, bmagyar commented on compliance_controller/wrench_to_joint_vel_pub/include/wrench_to_joint_vel_pub/compliant_control.h
> +  NUM_DIMS = 6  // 3 translational, 3 rotational dimensions
How about a single cost instead?

2019-11-12 22:51 UTC, bmagyar commented on compliance_controller/wrench_to_joint_vel_pub/src/wrench_to_joint_vel_pub/wrench_to_joint_vel_pub.cpp
> +  std::vector<double> damping = req.damping.data;
Const

2019-11-12 22:51 UTC, bmagyar commented on velocity_controllers/CHANGELOG.rst
> +0.13.4 (2018-06-26)
Don't make changes to this file please

2019-11-12 22:51 UTC, bmagyar commented on traj_or_jog_controller/include/traj_or_jog_controller/traj_or_jog_controller.h
> +#endif  // header guard
On melodic you have C++14 by default, this archaic tech can now be replaced by `#pragma once`

2019-11-12 22:51 UTC, bmagyar commented on ros_controllers/CHANGELOG.rst
> +
No meddling with changelogs please

2019-11-12 22:54 UTC, bmagyar requested changes

2019-11-12 22:54 UTC, bmagyar commented on compliance_controller/compliance_controller/CMakeLists.txt
> +
We proud ourselves here for our tests. They ensure that continued improvements to the controllers and the ros_control framework keep everything working. Could you please add some rostests that ensure some basic functionality? Look at joint traj controller or diff drive controller for good examples.

2019-11-13 21:19 UTC, AdamPettinger commented
Thanks for the feedback, I am making the requested changes. In terms of squashing it down, I am struggling to do so. This is my first big PR and unfortunately is a messy one :(. A lot of the early commits are not related to the compliance controller and are causing me problems.

Locally I was able to start with a fresh `ros-controls:melodic-devel` branch, and cherry pick the commits for the compliance controller. Then I rebased to squash it to 1-2 commits and everything looks good (only files changed are the ones we added, builds and runs as expected). At this point I am not sure if it is better to merge this branch with our `UTNuclearRobotics:melodic-devel` branch and force push it to update this PR, or to close the PR and open a new one, or to do something else entirely. Do you have insights here?

As for actual code changes, I will work to incorporate the changes requested here, as well as in the original PR for the kinetic branch

2019-11-13 22:09 UTC, bmagyar commented
First of all I suggest backing it all up. Avoid force pushing to your main branch, create a separate one for this MR and if you want to merge the end result back once its emerged here, so be it. 
Github allows for retargeting PRs including the source if I remember well... 

You should be able to do an interactive rebase. I suggest to do it in a couple of steps. First, review the commits that show up on this PR and drop all that don't belong to your team. This will eliminate the changelog changes and other artifacts of releasing. Then as a second step see if there are hacky commits (the message sometimes tells you) and drop those too. Now, try squashing the first few commits and move on from here. If you have massive conflicts, you may want to rethink your strategy and see if the commit causing it can be eliminated first.

2019-11-20 17:59 UTC, closed without merging

2019-11-20 18:00 UTC, AdamPettinger commented
Closed this PR to open a new, cleaner one with proper rebasing, some additional features, and some of the fixes requested here

2019-11-21 09:30 UTC, bmagyar commented
Thank you!

On Wed, 20 Nov 2019, 18:00 AdamPettinger, <notifications@github.com> wrote:

> Closed this PR to open a new, cleaner one with proper rebasing, some
> additional features, and some of the fixes requested here
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/ros-controls/ros_controllers/pull/434?email_source=notifications&email_token=AA24PYMMIDAC6TNG5LPQQGLQUV3K5A5CNFSM4JG7WEGKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEETJ3MI#issuecomment-556178865>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AA24PYJUKRT4FCEWIDSD5PLQUV3K5ANCNFSM4JG7WEGA>
> .
>