Fix: JointTrajectoryController tolerance checking using incorrect joint error
ros-controls/ros_controllers pull request #497
Opened 2020-07-09 07:25 UTC by dougsm

`state_joint_error_` is used as a temp variable inside a loop over joints in `updateStates`, so always contains the error values for the last joint in the loop.  As such, tolerance checking was only ever checking the error of the last joint, but against the tolerances for each joint. 

This simple fix just puts the correct error values into `state_joint_error_` before the tolerances are checked.

2020-07-22 00:19 UTC, dougsm commented
@bmagyar  I think this was initially introduced by your commit 99c035b1adaafb8c0e81ceae75ee0da0d95faf62

2020-09-25 06:54 UTC, bmagyar requested changes

2020-09-25 06:54 UTC, bmagyar commented on joint_trajectory_controller/include/joint_trajectory_controller/joint_trajectory_controller_impl.h
> +    state_joint_error_.acceleration[0] = 0.0;
```suggestion
    state_joint_error_.acceleration[0] = state_joint_error_.acceleration[i];
```

we don't have to know at this point if this is set to 0.0

2020-09-25 06:54 UTC, bmagyar commented on joint_trajectory_controller/include/joint_trajectory_controller/joint_trajectory_controller_impl.h
> +    state_joint_error_.position[0] = state_error_.position[i];
are you 100% sure that the indices here are correct?

2020-09-25 06:55 UTC, bmagyar commented
@dougsm sorry for the delay on this one

2020-09-25 07:08 UTC, bmagyar commented on joint_trajectory_controller/include/joint_trajectory_controller/joint_trajectory_controller_impl.h
> +    state_joint_error_.position[0] = state_error_.position[i];
Ok I think you are right but I have a aslightly different idea for a solution.

`state_joint_error_` is truly a local variable and therefore shouldn't even be a member. The scope of it is reduced entirely to this section, it's updated by `updateStates` which is a useless update, the code could be removed from there...

let me put a commit on top of your PR here

2020-09-25 07:27 UTC, bmagyar commented on joint_trajectory_controller/include/joint_trajectory_controller/joint_trajectory_controller_impl.h
> +    state_joint_error_.position[0] = state_error_.position[i];
due to StateSegment not being particularly realtime friendly I couldn't manage a good local var fix but I think this will do

2020-09-25 07:30 UTC, bmagyar commented
@dougsm could you give this a review/test please? I've rebased (for better CI) and added a commit on top

2020-10-06 07:33 UTC, bmagyar commented
@mateus-amarante @matthew-reynolds could you guys please give this a review/test?

2020-10-07 01:29 UTC, mateus-amarante reviewed
The update sounds correct! Before the update, all joint tolerances are compared to the error of the last joint.

I think the [tests](https://github.com/ros-controls/ros_controllers/blob/b551a652147a2095a9d0391b100cbc0043fac2ec/joint_trajectory_controller/test/joint_trajectory_controller_test.cpp#L1179-L1258) were not catching this because the forced error is applied to both joints of the rrbot through the `smoothing` parameter ([impl](https://github.com/ros-controls/ros_controllers/blob/b551a652147a2095a9d0391b100cbc0043fac2ec/joint_trajectory_controller/test/rrbot.cpp#L113-L145))

The tests should check the tolerance violation of each individual joint. One way to solve this would be by updating the interface of the rrbot to set the `smoothing` factor for each individual joint, then test the tolerance violation for each joint.

2020-10-09 23:58 UTC, mateus-amarante commented
> One way to solve this would be by updating the interface of the rrbot to set the smoothing factor for each individual joint, then test the tolerance violation for each joint.

#523 implements this idea

2020-10-10 20:24 UTC, bmagyar commented
@mateus-amarante your changes properly flag things up on #523 , I've cherry picked those tests onto this PR

2020-10-10 21:03 UTC, bmagyar approved these changes

2020-10-10 21:03 UTC, bmagyar commented
@dougsm thanks very much for spotting this and providing a fix.
@mateus-amarante many thanks for tracking down how we could properly test this!!

2020-10-10 21:03 UTC, merged