[joint_state_controller] Allow specification of joints or set specific order
ros-controls/ros_controllers pull request #565
Opened 2021-05-14 17:52 UTC by wxmerkt

Introduces a 'joints' parameter similar to other controllers in order to
be able to specify a subset of joints or a specific order of joints.
This is useful when the HardwareInterface exposes joints in an order
that is not desired or if certain joints are not meant to be published
by a controller. If not provided, the controller publishes all joints
and preserves backwards-compatibility.

2021-05-14 20:59 UTC, matthew-reynolds requested changes
This seems like a reasonable feature.

Personally I don't see a lot of value in this (Why would you care about the order of the joints? Is the small overhead of transporting all the joint states instead of a subset really an issue?), but I also see no downside to giving the option to users, so LGTM pending requested changes.

2021-05-14 20:59 UTC, matthew-reynolds commented on joint_state_controller/src/joint_state_controller.cpp
> +      std::vector<std::string> joint_names = hw->getNames();
```suggestion
      joint_names = hw->getNames();
```

2021-05-14 22:37 UTC, wxmerkt commented
Thanks for spotting the error!

> Why would you care about the order of the joints? 

Unfortunately not all downstream consumers of `joint_states` correctly set the order of the vector based on the joint names and have implicit assumptions on joint orders (including when URDF parsers order joints differently).

> Is the small overhead of transporting all the joint states instead of a subset really an issue?

Some downstream use cases we encountered don't select the required value from the vector, so having the option to have a subset e.g. under a different topic is a suitable workaround without republishing.

2021-05-14 23:25 UTC, matthew-reynolds approved these changes
LGTM. Shame we have to add upstream workarounds for poorly behaving downstream packages, but it's such a small and easy feature that may as well.

Thanks!

2021-05-25 15:22 UTC, wxmerkt commented
@matthew-reynolds I added the suggested fix. Is this good to merge?

2021-05-25 15:49 UTC, matthew-reynolds commented
Let's ping @bmagyar

2021-06-10 11:40 UTC, wxmerkt commented
@bmagyar could you please take a look at this?

2021-06-13 10:24 UTC, bmagyar approved these changes

2021-06-13 10:24 UTC, bmagyar commented
Thanks guys, looks good! I will try to put the release out today

2021-06-13 10:25 UTC, merged

2021-06-13 15:22 UTC, bmagyar commented
https://github.com/ros/rosdistro/pull/29881